import React, { useEffect } from "react";
import FadeIn from "./FadeIn";

const TermOfUse: React.FC = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="legal-page-wrapper">
      <FadeIn transitionDuration={700}>
        <div className="legal-content">
          <h1>Terms of Use (EULA)</h1>
          <p className="last-updated">Last updated: November 20, 2025</p>

          <p>
            These Terms of Use ("Terms") govern your use of the{" "}
            <strong>EasyWrite AI</strong> mobile application (the "App")
            operated by <strong>Phan Quang Duy</strong>.
          </p>
          <p>
            By downloading or using the App, you agree to be bound by these
            Terms. If you disagree with any part of the terms, then you may not
            access the App.
          </p>

          <div className="highlight-box">
            <h3>1. AI DISCLAIMER (IMPORTANT)</h3>
            <p>
              EasyWrite AI uses Artificial Intelligence (Google Gemini) to
              provide grammar checking and text generation.
            </p>
            <ul>
              <li>
                <strong>Accuracy:</strong> While we strive for accuracy, AI
                models can make mistakes ("hallucinations"). The suggestions,
                corrections, and emails generated by the App may not always be
                100% accurate, contextually correct, or grammatically perfect.
              </li>
              <li>
                <strong>No Professional Advice:</strong> The App is a tool for
                assistance only. It does not replace professional human editors,
                translators, or legal advice.
              </li>
              <li>
                <strong>User Responsibility:</strong> You are solely responsible
                for reviewing and verifying any content generated by the App
                before using, sending, or publishing it. We are not liable for
                any consequences resulting from the use of the generated content
                (e.g., sending an incorrect email to a boss).
              </li>
            </ul>
          </div>

          <h2>2. USER CONTENT & DATA</h2>
          <ul>
            <li>You retain ownership of any text you input into the App.</li>
            <li>
              You grant us a license to process your input text to provide the
              requested services (e.g., sending it to the AI provider).
            </li>
            <li>
              <strong>Local Storage:</strong> You acknowledge that your history
              and saved items are stored locally on your device. We are not
              responsible for data loss caused by deleting the app or device
              malfunction.
            </li>
            <li>
              You agree not to input any sensitive, confidential, or illegal
              content into the App.
            </li>
          </ul>

          <h2>3. PROHIBITED USES</h2>
          <p>You agree not to use the App:</p>
          <ul>
            <li>
              In any way that violates any applicable national or international
              law.
            </li>
            <li>
              To generate content that is hate speech, threatening, or promotes
              violence.
            </li>
            <li>To spam or overload the API service.</li>
            <li>To attempt to reverse engineer the App's source code.</li>
          </ul>

          {/* <h2>4. SUBSCRIPTIONS AND PURCHASES</h2>
          <ul>
            <li>
              <strong>Free Version:</strong> The App is provided for free with
              limitations and may display advertisements.
            </li>
            <li>
              <strong>Premium Subscription:</strong> We may offer a paid
              subscription ("Pro") to remove ads and unlock unlimited features.
            </li>
            <li>
              <strong>Payments:</strong> All payments are processed through the
              Apple App Store or Google Play Store. We do not store your credit
              card information.
            </li>
            <li>
              <strong>Refunds:</strong> Refund requests must be made directly to
              Apple or Google in accordance with their refund policies.
            </li>
          </ul> */}

          <h2>4. SUBSCRIPTIONS AND PURCHASES</h2>
          <ul>
            <li>
              <strong>Free Version:</strong> The App is provided for free with
              limitations. {/* Đã xóa đoạn "and may display advertisements" */}
            </li>
            <li>
              <strong>Premium Subscription:</strong> We may offer a paid
              subscription ("Pro") to unlock unlimited features.{" "}
              {/* Đã xóa đoạn "remove ads" */}
            </li>
            <li>
              <strong>Payments:</strong> All payments are processed through the
              Apple App Store or Google Play Store. We do not store your credit
              card information.
            </li>
            <li>
              <strong>Refunds:</strong> Refund requests must be made directly to
              Apple or Google in accordance with their refund policies.
            </li>
          </ul>

          <h2>5. INTELLECTUAL PROPERTY</h2>
          <p>
            The App and its original content (excluding User Content), features,
            and functionality are and will remain the exclusive property of Phan
            Quang Duy and its licensors.
          </p>

          <h2>6. LIMITATION OF LIABILITY</h2>
          <p>
            In no event shall Phan Quang Duy, nor its directors, employees,
            partners, agents, suppliers, or affiliates, be liable for any
            indirect, incidental, special, consequential or punitive damages,
            including without limitation, loss of profits, data, use, goodwill,
            or other intangible losses, resulting from your access to or use of
            or inability to access or use the App.
          </p>

          <h2>7. CHANGES</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace
            these Terms at any time.
          </p>

          <h2>8. CONTACT US</h2>
          <p>
            If you have any questions about these Terms, please contact us at:{" "}
            <a href="mailto:phanquangduytvt.work@gmail.com">
              phanquangduytvt.work@gmail.com
            </a>
          </p>
        </div>
      </FadeIn>
    </div>
  );
};

export default TermOfUse;
